services:
  - type: web
    name: treasury-vault-timer-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HELIUS_API_KEY
        value: 466f06cf-0f8e-4f05-9c46-a95cb4a83f67
